### ISSUE TITLE
Fails to conifgure on Slackware?

### ISSUE THREAD

**Issue by Xylemon** [bbidulock/wmblob#1]
I'm trying to compile wmblob 1.0.4 on Slackware 14.1 64bit with everything using current packages, and it fails to create a makefile claiming it can't find libX11:

checking for XOpenDisplay in -lX11... no
configure: error: ***\* could not find libX11

The error in config.log:

configure:4094: checking for X
configure:4233: gcc -o conftest    conftest.c -lX11  >&5
configure:4233: $? = 0
configure:4283: result: libraries , headers 
configure:4290: checking for XOpenDisplay in -lX11
configure:4315: gcc -o conftest    conftest.c -lX11   -L >&5
gcc: error: missing argument to '-L'
configure:4315: $? = 1
configure: failed program was:
| /\* confdefs.h _/
| #define PACKAGE_NAME "wmblob"
| #define PACKAGE_TARNAME "wmblob"
| #define PACKAGE_VERSION "1.0.4"
| #define PACKAGE_STRING "wmblob 1.0.4"
| #define PACKAGE_BUGREPORT "jlh-at-gmx-dot-ch"
| #define PACKAGE_URL ""
| #define PACKAGE "wmblob"
| #define VERSION "1.0.4"
| /_ end confdefs.h.  _/
| 
| /_ Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  _/
| #ifdef __cplusplus
| extern "C"
| #endif
| char XOpenDisplay ();
| int
| main ()
| {
| return XOpenDisplay ();
|   ;
|   return 0;
| }
configure:4324: result: no
configure:4334: error: *_*\* could not find libX11

**Comment by bbidulock** [comment]
You can check the Archlinux PKGBUILD [from here](https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wmblob).  The way I got around it was:

```
./configure --prefix=/usr \
            --mandir=/usr/share/man \
            --x-includes=/usr/include/X11 \
            --x-libraries=/usr/lib/X11
```

**Comment by Xylemon** [comment]
Thanks! That worked and I was able to finish the SlackBuild for this!
